### Cập nhật vị trí vật tư
PATCH {{host}}/{{commonPath}}/{{vatTuId}}/update-supply-location
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "idToMay": 1027,
  "idGiaKe": 1029,
  "idNgan": 1005
}

### Xóa ảnh vật tư
DELETE {{host}}/{{commonPath}}/{{vatTuId}}//delete-supplies-image?currentImagePath=D%3A%5CImages%5C5%5CVattu1.jpg
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Danh sách vị trí của vật tư theo cấp
GET {{host}}/{{commonPath}}/{{parentId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}