### Hiển thị chi tiết kiểm kê: Quét QR Code kiểm kê/ Nhập mã tay
GET {{host}}/{{kiemkePath}}/{{maVatTu}}
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}


### Cập nhật DFF vật tư
PATCH {{host}}/{{kiemkePath}}/{{vatTuId}}/{{kyKiemKeChiTietId}}/update-supplies-dff?soLuongKiemKe=100
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

{
  "soLuongMatPhamChat": 2,
  "phanTramMatPhamChat": 2,
  "soLuongKemPhamChat": 3,
  "phanTramKemPhamChat": 4,
  "soLuongDong": 5,
  "soLuongDeNghiThanhLy": 6,
  "phanTramDong": 7,
  "tsKemPcMatPc": 8
}

### Cập nhật QTY vật tư
PATCH {{host}}/{{kiemkePath}}/{{vatTuId}}/update-supplies-qty?soLuongKiemKe=100
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

### Danh sách kỳ kiểm kê
GET {{host}}/{{kiemkePath}}
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

### Hiển thị kỳ kiểm kê hiện tại
GET {{host}}/{{kiemkePath}}/current-inventory-check
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}






