### Hiển thị chi tiết kiểm kê: Quét QR Code kiểm kê/ Nhập mã tay
GET {{host}}/{{kiemkePath}}/{{vatTuId}}
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

### Cập nhật vị trí vật tư
PATCH {{host}}/{{kiemkePath}}/{{vatTuId}}/{{idViTri}}
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

{
  "IdToMay": 5,
  "IdGiaKe": 8,
  "IdNgan": 9,
  "IdHop": 10,
  "TenToMay": "Tổ máy 01",
  "TenGiaKe": "Kệ 02",
  "TenNgan": "Ngăn 01",
  "TenHop": "Hộc 1"
}




