### Danh sách vật tư
GET {{host}}/{{muaSamVatTuPath}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Chi tiết vật tư mua sắm
GET {{host}}/{{muaSamVatTuPath}}/{{vatTuId}}/chi-tiet-vat-tu
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

### Thêm mới vật tư k có trong hệ thống
POST {{host}}/{{muaSamVatTuPath}}/them-moi-vat-tu
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tenVatTu": "Cáp điện tròn phi 18",
  "donViTinh": "mét",
  "ghiChu": "200 mét, có bọc xốp",
  "thongSoKyThuat": "hàng loại 1"
}


### Danh sách Phiếu cung ứng
GET {{host}}/{{muaSamVatTuPath}}/list-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Thêm mới phiếu cung ứng
POST {{host}}/{{muaSamVatTuPath}}/them-phieu-cung-ung?moTa=phiếu cung ứng vật tư số 19
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
  {
    "idVatTu": 4,
    "tenVatTu": "fuchsyloken",
    "donViTinh": "CHai",
    "isSystemSupply": true,
    "soLuong": 10,
    "thongSoKyThuat": "màu xanh, loại 10mm, dài 5cm",
    "ghiChu": ""
  },
  {
    "idVatTu": 1006,
    "tenVatTu": "Cáp điện tròn phi 18",
    "donViTinh": "mét",
    "isSystemSupply": true,
    "soLuong": 1000,
    "thongSoKyThuat": "hàng loại 1",
    "ghiChu": "200 mét, có bọc xốp"
  },
  {
    "idVatTu": 2,
    "tenVatTu": "Ống nhựa HDPE Toàn Thắng",
    "donViTinh": "mét",
    "isSystemSupply": false,
    "soLuong": 1000,
    "thongSoKyThuat": "màu xanh",
    "ghiChu": "1000 mét phi 20"
  }
]

### Hiển thị thông tin chi tiết phiếu cung ứng
GET {{host}}/{{muaSamVatTuPath}}/{{supplyTicketId}}/chi-tiet-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Xóa một phiếu cung ứng
DELETE {{host}}/{{muaSamVatTuPath}}/{{supplyTicketId}}/xoa-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}