### Danh sách vật tư để chọn mua
GET {{host}}/{{muaSamVatTuPath}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Chi tiết vật tư mua sắm
GET {{host}}/{{muaSamVatTuPath}}/{{vatTuId}}/chi-tiet-vat-tu
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

### Danh sách Phiếu cung ứng
GET {{host}}/{{muaSamVatTuPath}}/list-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Thêm mới phiếu cung ứng
POST {{host}}/{{muaSamVatTuPath}}/them-phieu-cung-ung?moTa=phiếu cung ứng vật tư số 50
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "description": "string",
  "supplyTicketDetails": [
    {
      "gioHangId": 150,
      "vatTuId": 33,
      "isSystemSupply": true,
      "soLuong": 10,
      "thongSoKyThuat": "Trường hợp nghỉ hưu sớm",
      "ghiChu": "ghi chú test"
    }
  ]
}

### Hiển thị thông tin chi tiết phiếu cung ứng
GET {{host}}/{{muaSamVatTuPath}}/{{supplyTicketId}}/chi-tiet-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Xóa một phiếu cung ứng
PATCH {{host}}/{{muaSamVatTuPath}}/{{supplyTicketId}}/xoa-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Danh sách các kho hàng
GET {{host}}/{{muaSamVatTuPath}}/danh-sach-kho
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Danh sách nhóm
GET {{host}}/{{muaSamVatTuPath}}/danh-sach-nhom
Content-Type: application/json
Authorization: Bearer {{accessToken}}