### Danh sách vật tư
GET {{host}}/{{muaSamVatTuPath}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Chi tiết vật tư mua sắm
GET {{host}}/{{muaSamVatTuPath}}/{{vatTuId}}/chi-tiet-vat-tu
Content-Type: application/json
kikiemke-id: {{kikiemkeId}}
Authorization: Bearer {{accessToken}}

### Danh sách Phiếu cung ứng
GET {{host}}/{{muaSamVatTuPath}}/list-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Thêm mới phiếu cung ứng
POST {{host}}/{{muaSamVatTuPath}}/them-phieu-cung-ung?moTa=phiếu cung ứng vật tư số 19
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "description": "string",
  "supplyTicketDetails": [
    {
      "gioHangId": 38,
      "vatTuId": 4,
      "tenVatTu": "fuchsyloken",
      "donViTinh": "Chai",
      "isSystemSupply": true,
      "soLuong": 10,
      "thongSoKyThuat": "màu xanh, loại 10mm, dài 5cm",
      "ghiChu": "",
      "image": "/IMGVatTu/4/1.jpg"
    }
  ]
}

### Hiển thị thông tin chi tiết phiếu cung ứng
GET {{host}}/{{muaSamVatTuPath}}/{{supplyTicketId}}/chi-tiet-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Xóa một phiếu cung ứng
PATCH {{host}}/{{muaSamVatTuPath}}/{{supplyTicketId}}/xoa-phieu-cung-ung
Content-Type: application/json
Authorization: Bearer {{accessToken}}